name: static

on:
  push:
  pull_request:

jobs:
  static:
    runs-on:
     - ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        pg_version: [15, 16]
        compiler: [clang, gcc]
    env:
      LLVM_VER: 12
      CPU: ${{ matrix.cpu }}
      CHECK_TYPE: static
      COMPILER: ${{ matrix.compiler }}
    steps:
      - name: Checkout extension code into workspace directory
        uses: actions/checkout@v4
        with:
          path: orioledb
      - name: Get the required tag name
        shell: bash
        run: |
          echo "PGTAG=$(grep '^${{ matrix.pg_version }}: ' orioledb/.pgtags | cut -d' ' -f2-)" >> $GITHUB_ENV
      - name: Checkout PostgreSQL code into workspace directory
        uses: actions/checkout@v4
        with:
          repository: orioledb/postgres
          ref: ${{ env.PGTAG }}
          path: postgresql
      - name: Setup prerequisites
        run: bash ./orioledb/ci/prerequisites.sh
      - name: Build
        run: bash ./orioledb/ci/build.sh
      - name: Static analysis
        run: bash ./orioledb/ci/static.sh
